name: lib2
option:
  items:
    - name: test
      choices:
        - A
        - B
        - C
        - D
      links:
        - project: lib1
          option: test
script:
  sources:
    - dir: script
  imports:
    - local:
        dir: ./.test/lib1
    - local:
        dir: ./.test/lib3
config:
  sources:
    - dir: config
