name: lib1
option:
  items:
    - name: test
      default: 1234
      choices: [ "1234", "5678", "0000" ]
    - name: lib2_test
      export: lib2.test
      hidden: true
      compute: >-
        test == '1234' ? 'A' : (test == '5678' ? 'B' : (test == '0000' ? 'C' : nil))
    - name: app_test
      export: app1.test
      hidden: true
      compute: >-
        test == '1234' ? 'a' : (test == '5678' ? 'b' : (test == '0000' ? 'c' : nil))
    - name: local
      optional: true
dependency:
  items:
    - link: "dir:./.test1/lib2"
resource:
  items:
    - dir: script
