name: lib2
option:
  items:
    - name: test
      choices:
        - A
        - B
        - C
        - D
      assigns:
        - project: lib1
          option: test
imports:
  - link: "dir:./.test1/lib1"
  - link: "dir:./.test1/lib3"
sources:
  - dir: script
  - dir: config
    files:
      - test.dcfg.yml
    match: test == "A"
