name: lib2
option:
  items:
    - name: test
      choices:
        - A
        - B
        - C
        - D
      assigns:
        - target: lib1.test
dependency:
  items:
    - link: "dir:./.test1/lib1"
    - link: "dir:./.test1/lib3"
resources:
  items:
    - dir: script
    - dir: config
      includes:
        - test.dcfg.yml
      match: test == "A"
