name: lib2
option:
  items:
    - name: test
      export: lib1.test
      choices: [ A, B, C, D ]
dependency:
  items:
    - link: "dir:./.test1/lib1"
    - link: "dir:./.test1/lib3"
resource:
  items:
    - dir: script
    - dir: config
      includes:
        - test.dcfg.yml
      match: test == "A"
