name: lib2
option:
  items:
    - name: test
      choices:
        - A
        - B
        - C
        - D
      assigns:
        - project: lib1
          option: test
script:
  sources:
    - dir: script
  imports:
    - local:
        dir: ./.test1/lib1
    - local:
        dir: ./.test1/lib3
config:
  sources:
    - dir: config
      files:
        - test.yml
      match: test == "A"
