name: app1
runtime:
  minVersion: 1.0.0
  maxVersion: 2.0.0
option:
  items:
    - name: test
      default: c
      choices:
        - a
        - b
        - c
        - d
      assigns:
        - project: lib1
          option: test
          mapping: >-
            value == 'a' ? '1234' : (value == 'b' ? '5678' : (value == 'c' ? '0000' : nil))
        - project: lib2
          option: test
          mapping: upper(value)
    - name: test_object
      type: object
      default: '{"a": 1, "b": 2}'
      assigns:
        - project: lib3
          option: test
          mapping: value.b
    - name: test_array
      type: array
      default: '[1, 2, 3]'
      assigns:
        - project: lib4
          option: test
          mapping: value[1]
  checks:
    - _os == 'linux'
    - test != 'd'
    - test_object.a == 1
    - test_array[0] == 1
dependency:
  items:
    - link: "dir:./.test1/lib1"
      match: test == 'a'
    - link: "dir:./.test1/lib2"
      match: test == 'a'
resource:
  items:
    - dir: script
      match: test == 'a' || test == 'b'
    - dir: config
      includes:
        - test1.dcfg.yml
      match: test == 'a' || test == 'b'
imports:
  - link: "dir:./.test1/lib1"
    match: test == 'a'
  - link: "dir:./.test1/lib2"
    match: test == 'a'
sources:
  - dir: script
    match: test == 'a' || test == 'b'
  - dir: config
    files:
      - test1.dcfg.yml
    match: test == 'a' || test == 'b'
