name: lib4
script:
  sources:
    - dir: script
  imports:
    - link: "dir:./.test1/lib2"
    - link: "dir:./.test1/app1"
#    - link: "dir:./.test1/lib-err"
#    - link: "git:https://github.com/orz-dsh/dsh#ref=main"
