name: lib4
script:
  sources:
    - dir: script
  imports:
    - local:
        dir: ./.test1/lib2
    - local:
        dir: ./.test1/app1
#    - local:
#        dir: ./.test1/lib-err
#    - git:
#        url: https://github.com/orz-dsh/dsh
#        ref: main
